--!strict

-- local ReplicatedStorage = game:GetService("ReplicatedStorage")
-- local ServerScriptService = game:GetService("ServerScriptService")

-- local CompyServerScripts = ServerScriptService.CompyAgent
-- local CompySharedScripts = ReplicatedStorage.CompyAgent

-- local Config = require(CompySharedScripts.Config)
-- local Simulation = require(CompyServerScripts.Core.Simulation)

-- local simulation = Simulation.new(Config)
-- simulation:Start()

-- game:BindToClose(function(): ()
-- simulation:Stop()
-- end)

-- print("[CompyAgent] Server simulation started")
